language: ruby
deploy:
  provider: heroku
  api_key:
    secure: riJk2yiT4KQs0j746ava3iyOQ00mZn5+JsRDkf47bimFEjt5fcX6akCBlVNsY9hOrG0+UZ8ZjFEzy8cy1MYf0wbfc+CnoZQ5y40oy3bd1QIw0p8vBfaq8fV8ZIpMh+JCaLKvEY1pkvjccTQMe32wJQ3tSVHCJLhjI99Tz1pG77zqtUzY+NWOuzC8gWrG3pzTSzTEFWgWq91g9EuVu/cXVnLSNumqrHNRRMCqbdzo3LWEohOvnfiea6iR9cibF4EEAgDC5QZMbJp0llI5sj6q4H99D5zY1kSmL4PRq3EQn967KbpoYJmeGgZkx8xB3l8n8BbEa+x7E0TliiDGesV0nzE2eBxus3AMzzziuqnsjUMzW2E9haDLrMHvkcEcJFiv6U01r5KoV1f9zx0k0bIoB2QAok27sb9Iu5lzFId9XpLYAqCqaChceO1lof7pY1YokQtrTDSjprLNZDuhnzw3K49tqFJIKzlievFBsvhwW0GoJAEbsSVrA8hBNHZt/Ph4/6SuU+YkopTE/2ZJcVRtneHWSxXNgKaEMhAWVONpvwYGaHStcSxwr1hlywtv0CJ1WVDarxOEFjKsW6mP3LqrRO7aOF4NXZcBoggcbvs3LFRZBAlAqn3JJ1LIUu06ZTiEQcFEzlROtL5mA+5nQ8HyT8L1JYQ9u73GZj5JV3azU7k=
  app: jobsaver
  on:
    repo: mikeyhew/jobsaver
